### ISSUE TITLE
PCBnew doesn't work on nickoe builds

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#123]

**Comment by adamwolf** [comment]
Working on this today.

**Comment by adamwolf** [comment]
This is an issue where the rpath for Python things is empty.  We explicitly add the rpath, and we verify it's set.  I need to read the build logs for the nickoe stuff to make sure that is happening.

**Comment by adamwolf** [comment]
I am seeing a few issues.  The Python framework's Current symlink is turning into a copy during fixup_bundle, and the rpath is gone on the binaries after fixup_bundle.  I am almost certain these were not the case before I backported the BundleUtilities from 3.10.x to 3.6.  I am reverting my build system to 3.10.2 and seeing if this is a regression or something more serious.

**Comment by adamwolf** [comment]
OK, fixed all the issues I found, like fixup_bundle clobbering some rpaths and destroying symlinks, and there's *some* reference to python-dest at this point.  I need to find it, and make it relative.

**Comment by adamwolf** [comment]
I think I fixed it in #127 !  @nickoe, please remove the build/src/kicad directory (or the whole build/ directory) before builds tonight, as I modified one of the kicad patches in this.

**Comment by nickoe** [comment]
Ok. Done.

http://ci.kicad-pcb.org/job/osx-kicad-adam-new-head/145/console

**Comment by adamwolf** [comment]
It built.  I'll download it, check that it works, and hopefully close out
some issues!

**Comment by adamwolf** [comment]
Fixed!
