### ISSUE TITLE
Setup DMG notes

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#13]
Include diagnostic information in the DMG, including the script version, build options, source versions, and build parameters.

**Comment by adamwolf** [comment]
I am not 100% sure we need this.  Do other folks think this is important? I had it in the nightlies since forever, but I am not sure I have ever seen anyone use them.

**Comment by nickoe** [comment]
I don't think this is overly important. Usually getting the version of kicad itself is a good enough indicator of what version is used of other things, although it is not always exact. So I don't think this is required for v5.
