### ISSUE TITLE
STEP export uses wrong path

### ISSUE THREAD

**Issue by sethhillbrand** [wayneandlayne/kicad-mac-builder#137]
Exporting a STEP file from pcbnew tries to execute the command:
/Applications/KiCad/kicad.app/Contents/Applications/pcbnew.app/Contents/MacOS/kicad2step

But the application is actually
/Applications/KiCad/kicad.app/Contents/MacOS/kicad2step

**Comment by adamwolf** [comment]
Thanks!  Can you write up instructions on how to export STEP, or link me to
some simple ones?

Adam

**Comment by sethhillbrand** [comment]
Here's a simple board file. 

Open pcbnew (stand alone)
Open this file
Go to File->Export->STEP
[led-pannel2.kicad_pcb.zip](https://github.com/wayneandlayne/kicad-mac-builder/files/2087192/led-pannel2.kicad_pcb.zip)

**Comment by adamwolf** [comment]
I think this is an issue in KiCad, actually.

in dialog_export_step.cpp,

it says

```
    wxFileName appK2S( wxStandardPaths::Get().GetExecutablePath() );
    appK2S.SetName( "kicad2step" );
```

Really, we need to get the path of the kicad main app, if we are on macos.  I will try to make a KiCad patch tomorrow for this.

**Comment by sethhillbrand** [comment]
OK.  Thanks for digging into this.
