### ISSUE TITLE
build.sh package-kicad-nightly downloads docs. Is this the intended behaivour?

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#156]
Is it intentional that the build configuration:

`build.sh package-kicad-nightly`

Also downloads the docs? From the README this supposedly does: Creates a DMG of "mostly just KiCad" in build/dmg.

**Comment by adamwolf** [comment]
Yes.  It needs to download the docs or else the help menus don't work.  It
is really just packages3d that is missing.

**Comment by adamwolf** [comment]
I'll clarifying in a DMG cleanup PR that will be up today.

**Comment by nickoe** [comment]
Ok, I was expecting it to only build kicad itself, and then stuff it in a dmg for redistribution. Intended to test pactches quickly. But ok.

**Comment by adamwolf** [comment]
Yeah, that's what I wanted it to be, but then a lot of things in KiCad
don't work, and as thin as the macOS team is, I'd rather not have to
support folks using nightlies and running into "known broken" things.

I hope that kicad-mac-builder makes it so each that lots and lots of mac
devs join and help :)
