### ISSUE TITLE
Wxwidgets is always rebuilt for target kicad

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#161]
Hi

It looks lige wxwidgets is rebuilt every time kicad is built. I was wondering about this because I saw this triend on the build times on jenkins.

![buildtimes](https://user-images.githubusercontent.com/352202/41939431-12392ad6-7996-11e8-8080-85efbaf79ccc.png)

The good last good build before the failures shortly before the build time increase is #176 with 3afb7bc7e17415f2d30a49a7fa810e3cb1f62eab and the first good build with long build times are #180 with e652a42a896355e7aee9233dbf94791edd6c93c2.

I don'ẗ think this is intended, and this is sort of against using this for easy contributions from osx people.

I originally started to look at this because I wanted to test a patch, where it seems like it is not applied when I add a `.patch` file in `kicad-mac-builder/patches/kicad/`

Keep in mind I started observing this yesterday so this test was made on 59ac73c87be70a3f2be4595b16b235713bbf4047.

I tested this with:
```
make  python wxpython wxwidgets six ngspice -j10
make  kicad -j10
```
The second make does something along the lines of this snippet:
```
make[3]: Nothing to be done for `CMakeFiles/python.dir/build'.
make[3]: Nothing to be done for `CMakeFiles/ngspice.dir/build'.
make[3]: Nothing to be done for `CMakeFiles/six.dir/build'.
[  2%] Performing update step for 'wxwidgets'
cd /Users/nickoe/kicad-mac-builder/kicad-mac-builder/mybuild/wxwidgets/src/wxwidgets && /Users/kicad/homebrew/Cellar/cmake/3.6.2/bin/cmake -P /Users/nickoe/kicad-mac-builder/kicad-mac-builder/mybuild/wxwidgets/tmp/wxwidgets-gitupdate.cmake
[ 22%] Built target python
[ 43%] Built target ngspice
[ 47%] Built target six
Current branch kicad/macos-wx-3.0 is up to date.
[ 50%] Performing configure step for 'wxwidgets'
cd /Users/nickoe/kicad-mac-builder/kicad-mac-builder/mybuild/wxwidgets/src/wxwidgets && CPPFLAGS=-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 MAC_OS_X_VERSION_MIN_REQUIRED=10.13 ./configure --prefix=/Users/nickoe/kicad-mac-buil$
er/kicad-mac-builder/mybuild/wxwidgets-dest --with-opengl --enable-monolithic --enable-aui --enable-utf8 --enable-html --enable-stl --disable-mediactrl --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=built$
n --with-zlib=builtin --with-expat=builtin --without-liblzma --with-macosx-version-min=10.13 CC=clang CXX=clang++
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking for --disable-gui... no
```

**Comment by nickoe** [comment]
It looks like the main change is the removal of that `UPDATE_DISCONNECTED` stuff in https://github.com/wayneandlayne/kicad-mac-builder/commit/36607c47e2697aee4e89ffe0cddfffe96779c748#diff-6dca1159af1638174248c8241c9f2928L32

I am not sure I understand why we need to remove this. If you want to rebuild wxwidgets on a CI you could just make sure the CI script will call the `wxwidgets-update `target.

**Comment by adamwolf** [comment]
It doesn't matter to me.

I removed the update_disconnected stuff when I was debugging something
else.  I wanted to make sure that clean builds work always, and I wanted to
know if wxwidgets pulled the tarball for example.  However, I maintain a
build machine that does it from scratch inside a brand new VM every single
build, so if this makes it easier for you, I'm fine putting it back in.
