### ISSUE TITLE
Investigate bringing KiCad source in via a submodule or something

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#3]
I see in the readme what is presented in the title of this issue. Whey would this be desirable? What is wrong with just having the script do normal git oprations on a repo in the workspace. Having it as a submodule does not add any advantage to this as far as I can see.

**Comment by adamwolf** [comment]
I would find it slightly easier to do actual development on  KiCad.  I
could make local changes, compile to see if they work, and wrap them up in
a dmg without recompiling.

This is not a high priority feature in the slightest.

**Comment by adamwolf** [comment]
This might be just doable by showing people how to mod the script to use SOURCE_URL for the kicad project vs GIT_URL.

**Comment by adamwolf** [comment]
I did this using SOURCE_DIR, and it worked well.  I'll close this once we have a 1 line note in the README about it.
