### ISSUE TITLE
Check footprints

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#31]
Are we including them correctly?  Are there extra or missing files?  Do they show up automatically?  Do we need to include tables or any configuration files?

**Comment by adamwolf** [comment]
If someone could check this on the newest builds from http://downloads.kicad-pcb.org/osx/testing/, it would be awesome.

**Comment by sethhillbrand** [comment]
The footprints are not currently included in the nightly builds.

**Comment by adamwolf** [comment]
Hmm. They should be!  Aren't they in the kicad/library directory?

**Comment by adamwolf** [comment]
Sorry if you saw that message, I was confused.  They are included in the unified builds, but they are not in the nightly build.  I think we are going to recommend all new users start with the unified builds.

If it makes more sense we can also include them in nightlies, but the idea was that nightlies would be small for people testing each day.  Unified builds are for users who want everything.

**Comment by sethhillbrand** [comment]
Ah!  That makes sense. ... However, in that case, I might suggest that the nightlies include footprints and not the 3d models.  The 3d models are ~2.5GB in the package.  The footprints would be about 95MB.  A user could design a complete board without the 3d models but not without footprints.

**Comment by adamwolf** [comment]
Nightlies shouldn't be including 3d models.  Please let me know if they do
for you.  I am comfortable adding footprints to the nightlies.

**Comment by sethhillbrand** [comment]
![image](https://user-images.githubusercontent.com/914826/40895905-c5f293b0-6766-11e8-81e0-72d1a6874a4b.png)

3.2GB in 20180602

**Comment by adamwolf** [comment]
Ah. That does not look like it came from the testing directory--it looks
like a traditional nightly, which may actually explain a bit of my
confusion from some of these questions :)

There are some problems with the current nightlies, and the new ones coming
out of this project fix a bunch of issues.  The ones corresponding to these
are located at http://downloads.kicad-pcb.org/osx/testing/.

**Comment by sethhillbrand** [comment]
My goodness!  Yes, I've only ever looked in the nightly directory.  I'll switch to the testing directory from here on out.

**Comment by adamwolf** [comment]
No problem.  Thanks for helping!
