### ISSUE TITLE
Check templates

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#34]
Are we including them correctly?  Are there extra or missing files?  Do they show up automatically?  Do we need to include tables or any configuration files?

**Comment by adamwolf** [comment]
If someone could check this on the newest builds from http://downloads.kicad-pcb.org/osx/testing/, it would be awesome.

**Comment by sethhillbrand** [comment]
Templates look correct under 10.13 

sym-lib-table looks out of date
