### ISSUE TITLE
Check example Python scripts

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#35]
Do we want to include them?  Are we including them correctly?  Are there extra or missing files?  Do they show up automatically?  Do we need to include tables or any configuration files?

**Comment by craftyjon** [comment]
I see a `doc/scripts` in the `/Applications/Kicad` folder that I'm not sure should be there.  If we need some of these scripts to ship to the end user (do we?) we should pick and choose rather than just copying the entire scripts folder.

**Comment by adamwolf** [comment]
The examples are inside demos/ in python_scripts_examples.
