### ISSUE TITLE
Think about migration from v4

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#36]
Is there anything special people need to do to upgrade from v4?  Should they backup their Application Support/kicad directory first?

**Comment by craftyjon** [comment]
Really it's too bad that we don't have a better config management system in place (hopefully this will be better for V6) so we should advise that people should back up their config files if they want to maintain preferences, or be prepared to re-set their settings to they way they like it.

**Comment by adamwolf** [comment]
Can we make a list of all the config file locations, and then make a script
to make a zip of them?  It might be prudent to do this on other platforms
too.

Beyond config files, I am worried about people overwriting their symbols
and footprints and encountering the new organizations (I think they're
great, I'm not complaining, I just don't want to break users who haven't
changed any system libraries since v4 came out).

Are there other things we need to think about beyond those three?

**Comment by adamwolf** [comment]
I poked the list to make sure that we have some general documentation available.

**Comment by adamwolf** [comment]
We are discussing this on the KiCad list.  Closing here.
