### ISSUE TITLE
Check library symbols

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#37]
Are we including them correctly?  Are there extra or missing files?  Do they show up automatically?  Do we need to include tables or any configuration files?

**Comment by adamwolf** [comment]
If someone could check this on the newest builds from http://downloads.kicad-pcb.org/osx/testing/, it would be awesome.

**Comment by sethhillbrand** [comment]
These look out of date.  The xilinx ones (e.g.) have been renamed and split.

**Comment by adamwolf** [comment]
This should be fixed by #134.  We can check tomorrow and I can close this out.  Thanks!
