### ISSUE TITLE
There exists a build.sh but there are manual instructions in the readme

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#4]
In the readme instructions to call generic cmake and make commands are presented, but yet there is a `build.sh` script in the source tree. What is the way it is supposed to be used on a CI?

**Comment by adamwolf** [comment]
In my CI, I use build.sh through a vagrant box.  This lets me use one CI
machine to build it inside of a 10.11 box, a 10.12 box, and a 10.13 box,
and the machines are "fresh" every time, so nothing from a build can stick
around.

When I'm on business travel, I like to build locally as often I do not have
internet.  I'll add a task to create a ci.sh to make it clearer, but
there's already a task to make the readme readable to other people.

**Comment by adamwolf** [comment]
Working on making this clearer on the https://github.com/wayneandlayne/kicad-mac-builder/tree/readme branch.

**Comment by adamwolf** [comment]
Closing after tweaking readme.
