### ISSUE TITLE
Fix ApplicationSupport race condition

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#43]
Right now, subsections drop their files into ApplicationSupport as a semi-staging area before going into a dmg.  This breaks down once we have unified builds and nightlies sharing that directory.

I think for now, maybe we install to a directory in each part's section, and then pull them from the dmg script?  What do folks think?

**Comment by craftyjon** [comment]
sgtm.  I think there is not much value in having the support dir exist outside of the final packaging step.
