### ISSUE TITLE
Make sure wx is importable by KiCad's Python

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#46]
During the CMake step, some folks are getting something like

```
-- Check for installed Python Interpreter -- found
-- Python module install path: /Users/wolf/wnl/kicad/clion/kicad/cmake-build-debug/kicad/kicad.app/Contents/Frameworks/python/site-packages
-- wxPython version 3.0 found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named wx
```

Is this only a problem at cmake time?  Is it on the Python search path by the end, after the `make install`?

**Comment by nickoe** [comment]
Maybe we need something like we have in the old builder:

"-DPYTHON_SITE_PACKAGE_PATH=" + os.path.realpath("wx/wx-bin/lib/python2.7/site-packages"),

**Comment by adamwolf** [comment]
I think we do, in CMakeLists.txt.

set( KICAD_CMAKE_ARGS ...   -DPYTHON_SITE_PACKAGE_PATH=${
wxwidgets_INSTALL_DIR}/lib/python2.7/site-packages ... )

I suspect the issue here is that we have installed wx into the python that
we're going to compile KiCad against and bundle with it, but not into the
Python that cmake is invoking during configure time.  I am not sure this is
actually a problem, beyond making noise that says 'error'.  I am going to
see if I can aim CMake at that python, and see if the error goes away
though.

**Comment by adamwolf** [comment]
@nickoe this should be fixed in master, please confirm after the nightlies and we can close.

**Comment by nickoe** [comment]
Well, it is building now. So I guess this can be closed.

**Comment by nickoe** [comment]
Please close this.

**Comment by adamwolf** [comment]
Really?  The message may be gone during build, but wx isn't importable from
KiCad's python yet.

**Comment by nickoe** [comment]
Originally when I mentioned this issue, somewhere else, you created this issue to track it. I thought you wanted to track the rest of the issue in https://github.com/wayneandlayne/kicad-mac-builder/issues/9. Either is fine for me though...

**Comment by adamwolf** [comment]
That's right.
