### ISSUE TITLE
Minimum CMake version requirement

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#5]
Is there any reason to require cmake 3.8? Can 3.6.2 be used?

**Comment by adamwolf** [comment]
I have no idea.  I use CLion frequently, and it uses 3.8.  If this is
something you want to help out on, I can definitely look into it real soon,
otherwise I'll put investigating this into the list of tasks for after this
is ready for v5.

**Comment by nickoe** [comment]
It is simply because my box has 3.6.2. I will test it when I get home to see if it works with earlier and may propose to change this.

**Comment by adamwolf** [comment]
Awesome!  I bet it works fine on 3.6.2, and if not, I have no problem with
making it work on that.

**Comment by nickoe** [comment]
It looks like it works fine with 3.6.2, but I have not yet made a successful build becuase of other issues that I will report.

**Comment by adamwolf** [comment]
Thanks!

**Comment by adamwolf** [comment]
Pulled it back to 3.6.2.  Closing.
