### ISSUE TITLE
'doc/' in KiCad/ in dmg?

### ISSUE THREAD

**Issue by adamwolf** [wayneandlayne/kicad-mac-builder#54]
There are example scripts or something in the KiCad directory in the DMG.  What are they?  Where do they belong?

**Comment by craftyjon** [comment]
This is just the contents of the `scripts/` folder in the kicad source tree.  I don't think any of this should be packaged.

**Comment by craftyjon** [comment]
Fixed in KiCad: b813eac254cc0f138839525943ee78e714173d4a

**Comment by adamwolf** [comment]
Confirmed.  Thanks!
