### ISSUE TITLE
No dmg's generated?

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#63]
When I run build.sh, I can't find any dmg files in the workspace. Where are they expected to be?

**Comment by adamwolf** [comment]
I changed the behavior of build.sh, and improved it in #65.

**Comment by adamwolf** [comment]
@nickoe this should be fixed in master, please confirm after the nightlies and we can close.

**Comment by nickoe** [comment]
Confirmed, I updated the cmake option to include those targets on the build server, but it is essentially the same as the build.sh.
