### ISSUE TITLE
Build failure after "Python built as a Framework."

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#74]
With the new change "Python built as a Framework." (https://github.com/wayneandlayne/kicad-mac-builder/commit/538c743e37bd002d1795acce51d032ca9ef5bc77) I get this build error:
```
09:54:39 Building './Python Launcher.app'
09:54:39 Copying files
09:54:39 Done.
09:54:39 test -d "/Applications/Python 2.7" || mkdir -p "/Applications/Python 2.7"
09:54:39 mkdir: /Applications/Python 2.7: Permission denied
```
See http://ci.kicad-pcb.org/job/osx-kicad-adam-new-head/94/console

Using `./build.sh package-kicad-unified package-kicad-nightly package-extras` to build.

**Comment by adamwolf** [comment]
Thanks!

Working on it.  This was trickier than expected.
